### ISSUE TITLE
【依頼】フリマアプリ挙動確認

### ISSUE THREAD

**Issue by dino-pg** [dino-pg/furima-34856#9]
フリマアプリのURL
https://furima-34856.herokuapp.com/

Basic認証のIDとパスワード
"admin"
"password"

出品者用のメールアドレスとパスワード
test@com
1111aa

購入者用のメールアドレスとパスワード
test@com2
1234aa

**Comment by mo1015** [comment]
ご提出ありがとうございます！
問題なく正常に動作することが確認できました！LGTMです！　
おめでとうございます🎉


**※確認したのは必須機能のみです。追加実装した機能については確認しておりません。
そのため追加機能を実装している場合は、正しく想定通りの挙動であるか、再度ご自身でご確認をお願い致します。**
![最終課題終了_おめでとう画像2](https://user-images.githubusercontent.com/62644781/114490345-a46eb400-9c4f-11eb-8acb-d4ede721ea57.png)
